import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import theme from "./Theme";
import { Box} from "@mui/material";
import Header from "@/components/Header";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <ToastContainer position="top-right" autoClose={3000} />
          <Box sx={{ p: 0, m: 0, height: "100vh", backgroundColor: "background.default", display: "flex", overflow: "hidden", flexDirection:"column", justifyContent:"center", alignItems:"center" }}>
           <Header />
           {children}
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
